# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typegroup',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typegroup',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
