# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180315_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typegroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
